language: python
sudo: required
dist: bionic
python:
  - "3.8"
virtualenv:
  system_site_packages: true
# command to install dependencies
install:
  - sudo apt-get update
  - sudo apt-get -y install python3-pyqt5
  - sudo pip install -r requirements.txt
script:
  - python app.py
